const reviews = [
  {
    id: "001",
    game: "The Witcher 3",
    text: "The storytelling is on another level. Exploration feels rewarding, and the side quests are often better than main quests in other games.",
    score: 10,
    user: { username: "MossKnight" },
    date: new Date(),
    likes: 7,
  },
  {
    id: "002",
    game: "Elden Ring",
    text: "Massive world, brutal fights, but so satisfying when you finally overcome a boss. A masterpiece in atmosphere.",
    score: 9,
    user: { username: "Ashborne" },
    date: new Date(),
    likes: 5,
  },
  {
    id: "003",
    game: "Cyberpunk 2077",
    text: "Rough launch, but with updates it’s turned into a rich RPG with excellent writing and style.",
    score: 8,
    user: { username: "NeonWolf" },
    date: new Date(),
    likes: 6,
  },
  {
    id: "004",
    game: "Hollow Knight",
    text: "Hauntingly beautiful. Tight controls, stunning art, and a world that begs to be explored.",
    score: 10,
    user: { username: "SilkSongSoon" },
    date: new Date(),
    likes: 9,
  },
  {
    id: "005",
    game: "Stardew Valley",
    text: "Relaxing yet addictive. Farming, fishing, and relationships keep me coming back every day.",
    score: 9,
    user: { username: "TurnipKing" },
    date: new Date(),
    likes: 3,
  },
  {
    id: "006",
    game: "Red Dead Redemption 2",
    text: "Probably the most immersive open world ever made. Slow-paced, but breathtaking in detail.",
    score: 10,
    user: { username: "Cowpoke89" },
    date: new Date(),
    likes: 8,
  },
  {
    id: "007",
    game: "Minecraft",
    text: "Endless creativity and freedom. Still one of the best games to play with friends even after all these years.",
    score: 10,
    user: { username: "BlockSmith" },
    date: new Date(),
    likes: 10,
  },
  {
    id: "008",
    game: "Dark Souls III",
    text: "Every death teaches you something. Brutal, beautiful, and rewarding once you embrace the challenge.",
    score: 9,
    user: { username: "HollowedHeart" },
    date: new Date(),
    likes: 4,
  },
  {
    id: "009",
    game: "Overwatch 2",
    text: "Fun when matches are balanced, but matchmaking can be frustrating. Still has addictive team fights.",
    score: 7,
    user: { username: "PulseTracer" },
    date: new Date(),
    likes: 2,
  },
  {
    id: "010",
    game: "God of War (2018)",
    text: "Powerful story and excellent combat. The father-son relationship made it unforgettable.",
    score: 10,
    user: { username: "NorseSlayer" },
    date: new Date(),
    likes: 6,
  },
  {
    id: "011",
    game: "Sekiro: Shadows Die Twice",
    text: "Relentless combat system that forces perfection. Frustrating at times, but the payoff is worth it.",
    score: 9,
    user: { username: "OneArmedWolf" },
    date: new Date(),
    likes: 8,
  },
  {
    id: "012",
    game: "The Legend of Zelda: Breath of the Wild",
    text: "Freedom to approach the world however you want. Exploration feels magical every time.",
    score: 10,
    user: { username: "KorokHunter" },
    date: new Date(),
    likes: 9,
  },
  {
    id: "013",
    game: "Among Us",
    text: "Simple but hilarious with friends. Loses its charm quickly if you play with randoms.",
    score: 7,
    user: { username: "SusMaster" },
    date: new Date(),
    likes: 3,
  },
  {
    id: "014",
    game: "Baldur’s Gate 3",
    text: "Incredible freedom in storytelling and choices. Easily one of the best RPGs in years.",
    score: 10,
    user: { username: "DiceRoller" },
    date: new Date(),
    likes: 10,
  },
  {
    id: "015",
    game: "Apex Legends",
    text: "Fast-paced and fun, with great movement mechanics. Can feel a bit repetitive after long sessions.",
    score: 8,
    user: { username: "WingmanMain" },
    date: new Date(),
    likes: 5,
  },
  {
    id: "016",
    game: "Resident Evil 4 Remake",
    text: "Tense, polished, and respectful to the original. Survival horror done right.",
    score: 9,
    user: { username: "GanadoHunter" },
    date: new Date(),
    likes: 7,
  },
  {
    id: "017",
    game: "Fortnite",
    text: "Not my usual style, but it’s fun with friends. Constant updates keep it fresh.",
    score: 7,
    user: { username: "BuildOrDie" },
    date: new Date(),
    likes: 4,
  },
  {
    id: "018",
    game: "Hades",
    text: "Fast, addictive combat with great replay value. The story progression through repeated runs is genius.",
    score: 9,
    user: { username: "UnderworldKing" },
    date: new Date(),
    likes: 6,
  },
  {
    id: "019",
    game: "Call of Duty: Modern Warfare II",
    text: "Solid gunplay, but multiplayer feels a bit stale compared to older entries.",
    score: 7,
    user: { username: "GhostMask" },
    date: new Date(),
    likes: 2,
  },
  {
    id: "020",
    game: "Terraria",
    text: "So much depth for a 2D game. Exploration, bosses, and building are all incredibly fun.",
    score: 9,
    user: { username: "PixelMiner" },
    date: new Date(),
    likes: 8,
  },
];

const data = { reviews };

export default data;
