const reviews = [
  {
    id: "001",
    game: "The Witcher 3: Wild Hunt",
    text: "The storytelling is on another level. Exploration feels rewarding, and the side quests are often better than main quests in other games.",
    score: 10,
    user: { username: "MossKnight" },
    date: new Date(),
    likes: 7,
  },
  {
    id: "002",
    game: "Elden Ring",
    text: "Massive world, brutal fights, but so satisfying when you finally overcome a boss. A masterpiece in atmosphere.",
    score: 9,
    user: { username: "Ashborne" },
    date: new Date(),
    likes: 5,
  },
  {
    id: "003",
    game: "Cyberpunk 2077",
    text: "Rough launch, but with updates it’s turned into a rich RPG with excellent writing and style.",
    score: 8,
    user: { username: "NeonWolf" },
    date: new Date(),
    likes: 6,
  },
  {
    id: "004",
    game: "Hollow Knight",
    text: "Hauntingly beautiful. Tight controls, stunning art, and a world that begs to be explored.",
    score: 10,
    user: { username: "SilkSongSoon" },
    date: new Date(),
    likes: 9,
  },
  {
    id: "005",
    game: "Stardew Valley",
    text: "Relaxing yet addictive. Farming, fishing, and relationships keep me coming back every day.",
    score: 9,
    user: { username: "TurnipKing" },
    date: new Date(),
    likes: 3,
  },
  {
    id: "006",
    game: "Red Dead Redemption 2",
    text: "Probably the most immersive open world ever made. Slow-paced, but breathtaking in detail.",
    score: 10,
    user: { username: "Cowpoke89" },
    date: new Date(),
    likes: 8,
  },
  {
    id: "007",
    game: "Minecraft",
    text: "Endless creativity and freedom. Still one of the best games to play with friends even after all these years.",
    score: 10,
    user: { username: "BlockSmith" },
    date: new Date(),
    likes: 10,
  },
  {
    id: "008",
    game: "Dark Souls III",
    text: "Every death teaches you something. Brutal, beautiful, and rewarding once you embrace the challenge.",
    score: 9,
    user: { username: "HollowedHeart" },
    date: new Date(),
    likes: 4,
  },
  {
    id: "009",
    game: "Overwatch 2",
    text: "Fun when matches are balanced, but matchmaking can be frustrating. Still has addictive team fights.",
    score: 7,
    user: { username: "PulseTracer" },
    date: new Date(),
    likes: 2,
  },
  {
    id: "010",
    game: "God of War (2018)",
    text: "Powerful story and excellent combat. The father-son relationship made it unforgettable.",
    score: 10,
    user: { username: "NorseSlayer" },
    date: new Date(),
    likes: 6,
  },
  {
    id: "011",
    game: "Sekiro: Shadows Die Twice",
    text: "Relentless combat system that forces perfection. Frustrating at times, but the payoff is worth it.",
    score: 9,
    user: { username: "OneArmedWolf" },
    date: new Date(),
    likes: 8,
  },
  {
    id: "012",
    game: "The Legend of Zelda: Breath of the Wild",
    text: "Freedom to approach the world however you want. Exploration feels magical every time.",
    score: 10,
    user: { username: "KorokHunter" },
    date: new Date(),
    likes: 9,
  },
  {
    id: "013",
    game: "Among Us",
    text: "Simple but hilarious with friends. Loses its charm quickly if you play with randoms.",
    score: 7,
    user: { username: "SusMaster" },
    date: new Date(),
    likes: 3,
  },
  {
    id: "014",
    game: "Baldur’s Gate 3",
    text: "Incredible freedom in storytelling and choices. Easily one of the best RPGs in years.",
    score: 10,
    user: { username: "DiceRoller" },
    date: new Date(),
    likes: 10,
  },
  {
    id: "015",
    game: "Apex Legends",
    text: "Fast-paced and fun, with great movement mechanics. Can feel a bit repetitive after long sessions.",
    score: 8,
    user: { username: "WingmanMain" },
    date: new Date(),
    likes: 5,
  },
  {
    id: "016",
    game: "Resident Evil 4 Remake",
    text: "Tense, polished, and respectful to the original. Survival horror done right.",
    score: 9,
    user: { username: "GanadoHunter" },
    date: new Date(),
    likes: 7,
  },
  {
    id: "017",
    game: "Fortnite",
    text: "Not my usual style, but it’s fun with friends. Constant updates keep it fresh.",
    score: 7,
    user: { username: "BuildOrDie" },
    date: new Date(),
    likes: 4,
  },
  {
    id: "018",
    game: "Hades",
    text: "Fast, addictive combat with great replay value. The story progression through repeated runs is genius.",
    score: 9,
    user: { username: "UnderworldKing" },
    date: new Date(),
    likes: 6,
  },
  {
    id: "019",
    game: "Call of Duty: Modern Warfare II",
    text: "Solid gunplay, but multiplayer feels a bit stale compared to older entries.",
    score: 7,
    user: { username: "GhostMask" },
    date: new Date(),
    likes: 2,
  },
  {
    id: "020",
    game: "Terraria",
    text: "So much depth for a 2D game. Exploration, bosses, and building are all incredibly fun.",
    score: 9,
    user: { username: "PixelMiner" },
    date: new Date(),
    likes: 8,
  },
];

const games = [
  {
    id: "001",
    title: "The Witcher 3: Wild Hunt",
    release_date: new Date("2015-05-19"),
    developer: "CD PROJEKT RED",
    developer_country: "Poland",
    cover_image:
      "https://upload.wikimedia.org/wikipedia/en/0/0c/Witcher_3_cover_art.jpg",
    reviews: [], // you can fill with relevant review objects
    average_score: null,
  },
  {
    id: "002",
    title: "Elden Ring",
    release_date: new Date("2022-02-25"),
    developer: "FromSoftware",
    developer_country: "Japan",
    cover_image:
      "https://upload.wikimedia.org/wikipedia/en/b/b9/Elden_Ring_Box_art.jpg",
    reviews: [],
    average_score: null,
  },
  {
    id: "003",
    title: "Cyberpunk 2077",
    release_date: new Date("2020-12-10"),
    developer: "CD PROJEKT RED",
    developer_country: "Poland",
    cover_image:
      "https://upload.wikimedia.org/wikipedia/en/9/9f/Cyberpunk_2077_box_art.jpg",
    reviews: [],
    average_score: null,
  },
  {
    id: "004",
    title: "Hollow Knight",
    release_date: new Date("2017-02-24"),
    developer: "Team Cherry",
    developer_country: "Australia",
    cover_image:
      "https://upload.wikimedia.org/wikipedia/en/thumb/0/04/Hollow_Knight_first_cover_art.webp/274px-Hollow_Knight_first_cover_art.webp.png",
    reviews: [],
    average_score: null,
  },
  {
    id: "005",
    title: "Stardew Valley",
    release_date: new Date("2016-02-26"),
    developer: "ConcernedApe",
    developer_country: "United States",
    cover_image:
      "https://upload.wikimedia.org/wikipedia/en/f/fd/Logo_of_Stardew_Valley.png",
    reviews: [],
    average_score: null,
  },
];

const reviews2 = [
  // The Witcher 3 (5)
  {
    id: "001",
    game: "The Witcher 3: Wild Hunt",
    text: "A sprawling masterpiece — story, characters and worldbuilding all soar. I lost weeks to this game and never once regretted it.",
    score: 10,
    user: { username: "MossKnight" },
    date: new Date("2025-03-12T10:15:00Z"),
    likes: 8,
  },
  {
    id: "002",
    game: "The Witcher 3: Wild Hunt",
    text: "Combat can feel clunky sometimes but the narrative and side quests are unmatched. A must-play for RPG fans.",
    score: 9,
    user: { username: "GreyRaven" },
    date: new Date("2025-06-02T14:30:00Z"),
    likes: 6,
  },
  {
    id: "003",
    game: "The Witcher 3: Wild Hunt",
    text: "Beautiful setting, unforgettable characters, though the pacing dragged a little mid-campaign. Still brilliant overall.",
    score: 9,
    user: { username: "Alder" },
    date: new Date("2025-01-21T08:45:00Z"),
    likes: 4,
  },
  {
    id: "004",
    game: "The Witcher 3: Wild Hunt",
    text: "Perfect combination of dark fantasy and meaningful choices. Mods only made it better — highly recommended.",
    score: 10,
    user: { username: "Patchwork" },
    date: new Date("2025-07-19T19:05:00Z"),
    likes: 7,
  },
  {
    id: "005",
    game: "The Witcher 3: Wild Hunt",
    text: "Some quests outshine the main story — excellent writing across the board. A little long, but worth every hour.",
    score: 10,
    user: { username: "ProffesionalBurglar" },
    date: new Date("2025-04-05T11:00:00Z"),
    likes: 5,
  },

  // Hollow Knight (5)
  {
    id: "006",
    game: "Hollow Knight",
    text: "Impossibly good level and boss design. The atmosphere is oppressive in the best way.",
    score: 10,
    user: { username: "SilkSongSoon" },
    date: new Date("2025-02-14T09:00:00Z"),
    likes: 9,
  },
  {
    id: "007",
    game: "Hollow Knight",
    text: "Beautiful, precise, and occasionally brutal. Exploration rewards patience and curiosity.",
    score: 9,
    user: { username: "Cinder" },
    date: new Date("2025-05-03T16:20:00Z"),
    likes: 7,
  },
  {
    id: "008",
    game: "Hollow Knight",
    text: "Gorgeous art and tight controls. A few bosses overstayed their welcome but overall a phenomenal Metroidvania.",
    score: 9,
    user: { username: "Understone" },
    date: new Date("2025-08-11T21:10:00Z"),
    likes: 6,
  },
  {
    id: "009",
    game: "Hollow Knight",
    text: "Every corner hides something brilliant. Short on hand-holding — exactly how I like it.",
    score: 10,
    user: { username: "Pivnich" },
    date: new Date("2025-03-29T07:40:00Z"),
    likes: 8,
  },
  {
    id: "010",
    game: "Hollow Knight",
    text: "A little opaque at first, but once you click with it, this game hooks you hard. Masterclass in design.",
    score: 10,
    user: { username: "Glint" },
    date: new Date("2025-09-02T12:00:00Z"),
    likes: 5,
  },

  // Elden Ring (4)
  {
    id: "011",
    game: "Elden Ring",
    text: "Open-world Soulsborne done right. Exploration and difficulty come together beautifully.",
    score: 10,
    user: { username: "Ashborne" },
    date: new Date("2025-01-10T18:00:00Z"),
    likes: 9,
  },
  {
    id: "012",
    game: "Elden Ring",
    text: "Huge, rewarding and occasionally overwhelming. Best experienced with a willingness to die and learn.",
    score: 9,
    user: { username: "OneArmedWolf" },
    date: new Date("2025-04-22T13:30:00Z"),
    likes: 6,
  },
  {
    id: "013",
    game: "Elden Ring",
    text: "Landscape and bosses are spectacular, but some late-game balance issues annoyed me. Still fantastic overall.",
    score: 9,
    user: { username: "RuinSeeker" },
    date: new Date("2025-06-28T05:25:00Z"),
    likes: 4,
  },
  {
    id: "014",
    game: "Elden Ring",
    text: "Immersive and punishing — a glorious challenge. The best kind of expensive-sounding failure.",
    score: 10,
    user: { username: "SilkSongSoon" },
    date: new Date("2025-02-07T20:50:00Z"),
    likes: 7,
  },

  // Cyberpunk 2077 (3)
  {
    id: "015",
    game: "Cyberpunk 2077",
    text: "Pre-patches it was rough, but the updated experience is slick with a terrific setting. Still some rough edges.",
    score: 8,
    user: { username: "NeonWolf" },
    date: new Date("2025-05-18T11:11:00Z"),
    likes: 5,
  },
  {
    id: "016",
    game: "Cyberpunk 2077",
    text: "Gorgeous visuals and strong narrative beats. Performance varies, but atmosphere sells it.",
    score: 8,
    user: { username: "Glimmer" },
    date: new Date("2025-07-01T09:09:00Z"),
    likes: 3,
  },
  {
    id: "017",
    game: "Cyberpunk 2077",
    text: "Ambitious and stylish, occasionally buggy but the core story and city never stopped impressing me.",
    score: 7,
    user: { username: "SilkSongSoon" },
    date: new Date("2025-08-23T22:45:00Z"),
    likes: 2,
  },

  // Stardew Valley (3)
  {
    id: "018",
    game: "Stardew Valley",
    text: "Pure comfort gameplay. Easy to sink dozens of hours into a tiny peaceful life.",
    score: 9,
    user: { username: "TurnipKing" },
    date: new Date("2025-03-03T07:00:00Z"),
    likes: 6,
  },
  {
    id: "019",
    game: "Stardew Valley",
    text: "Charming and relaxing with a ton of content. Multiplayer is a lovely addition.",
    score: 9,
    user: { username: "Fieldhand" },
    date: new Date("2025-06-16T15:45:00Z"),
    likes: 4,
  },
  {
    id: "020",
    game: "Stardew Valley",
    text: "A warm, simple loop that nails progression and variety. Not flashy, but delightful.",
    score: 8,
    user: { username: "ProfessionalBurglar" },
    date: new Date("2025-09-05T10:30:00Z"),
    likes: 3,
  },
];

const data = { reviews, games, reviews2 };

export default data;
